babel/broccoli-babel-transpiler

package.json

New version of 6to5 has ```for ... in``` loops switched to regular ```for``` loops for arrays.
This means if anything loads Ember before compilation (eg emberscript), the prototype extensions won't be iterated over
related: https://github.com/ember-cli/ember-cli/issues/2999
cc @stefanpenner @sebmck @rwjblue
Let me know if you want me to bump package version here too

bump 6to5 version

---

index.js

This begs the question to me, why can't `broccoli-persistent-filter` have `optionsHash()` implementation by default as well and assign `this.options`? Or even `broccoli-filter`...why doesn't *it* assign `this.options`?
Basically, just starting this PR to discuss how we can reduce the boilerplate required to use `broccoli-persistent-filter` and since this is the first consumer, seems appropriate to discuss here.

Defer to super implementation Filter#cacheKeyProcessString()

---

README.md
fixtures/dep-graph.json
index.js
package.json
test.js

This allows for a JSON file to be written into the tree that describes the modules in the tree. This JSON file can then be used to perform dependency graph resolution. /cc @stefanpenner

Introduce Module Metadata export

---

index.js
package.json

Prior to this commit output and input paths were unstable due to the fact broccoli-filter did not use the broccoli rebuild api.

Use cauliflower-filter for stable paths

---

package.json

South of 1.0.4 there was a bug where directories would get written to CWD. In 1.0.4 that is fixed. See https://github.com/caitp/cauliflower-filter/pull/9 for more details.

Stick Cauliflower-filter at 1.0.4

---

README.md
index.js
package.json

The current implementation is just a quick and dirty patch.
1. Having this option in the plugin is something that will be accepted?
2. How I see it happening is:
1. have the plugin be an object/plugin of its own instead of extending from `broccoli-filter`
2. do the transpilation, build a transpiled tree internally for further processing
3. if `browserPolyfill` is set, prepend the polyfill to the transpiled tree and just then return it

[proposal] browserPolyfill option

---

index.js
package.json
test.js

Prior to this commit it was possible to have `imports` and the files in
the cache to differ based on options passed into Babel. This commit
makes sure we are always dealing with extensionless names.

Ensure import names are the same

---

index.js

This allows devs to effectively debug and undstand where cache hits are
coming from.

Adding name property

---

index.js
test.js

Almost fixes #54. One other issue remains.
It doesn't look like Windows support is coming anytime soon upstream babel/babel/pull/2290, so we need to force the Unix newline.

Ignore Windows newlines

---

index.js
test.js

I was having hack of a time getting the expected output as I was modifying the option's method, `resolveModuleSource`.

[BUGFIX] cache not clearing reliably when modifying options

---

README.md
fixtures/plugin-a/index.js
fixtures/plugin-a/package.json
fixtures/plugin-b/index.js
fixtures/plugin-b/package.json
index.js
package.json
test.js

This is a backport of #89 to the v5.x branch.

Allow plugins to bust the cache.

---

expectations/classes.js
fixtures/files/fixtures-classes.js
index.js
package.json
test.js

This PR introduces the idea of declaring what runtime transforms you intend on using. This is meant to be a stick for projects that would like only allow certain runtime helpers to be used.
@Turbo87 😢  No I was not aware of the forking.
/cc @stefanpenner

Introduce helper whitelist

---

README.md
index.js
package.json
test.js

We can always bring this back if it’s deemed useful.

Remove untested `exportModuleMetadata` option.

---

.travis.yml

Updated tested Node versions to align with [Ember's LTS policy](http://emberjs.com/blog/2016/09/07/ember-node-lts-support.html#toc_node-js-0-10-node-js-0-12).

TravisCI: Update tested Node versions.

---

index.js

Prevents errors from passing through all options to `babel` when using `annotation` / `description` options.
These are used locally by the builder system and should not end up in babel invocation.

Ensure common local plugin options do not error.

---

package.json

This was only needed while v6.0.0 was in beta.

package.json: Remove distTag override

---

index.js
test.js

This change enables correct caching of parallelizable plugin objects

Caching for plugin objects with baseDir() and cacheKey()

---

README.md

[Rendered](https://github.com/pablobm/broccoli-babel-transpiler/blob/explain-babel-6/README.md).
After working with version v5 of this plugin, today I tried v6 and was very confused that it wasn't working as expected. After some research, I figured out it was due to the changes in Babel 6.
I thought an example like this would have been useful, so here it is for the benefit of future developers.

Explain usage to people not familiar with Babel 6

---

lib/parallel-api.js
package.json
test.js
yarn.lock

Currently there is one worker pool per installation of broccoli-babel-transpiler. For projects where all dependencies are on the same babel version this is not a problem.
However, when dependencies require a mix of babel 5.x and 6.x (for example during upgrade), this can result in dozens of installations of broccoli-babel-transpiler. Since there is one pool per installation, this results in way too many workers.
This PR limits the number of worker pools to one per version of babel-core. The pool state is stored on the global 'process' as 'v1/broccoli-babel-transpiler/workerpool/babel-core-X.X.X'.

Limit to single worker pool per version of babel-core

---

.travis.yml

Resolves https://github.com/babel/broccoli-babel-transpiler/issues/129
Note that this PR targets the `v5.x` branch where this is most important right now and should be merged upwards eventually.
/cc @stefanpenner

CI: Use `skip_cleanup` to not revert `auto-dist-tag` adjustment

---

lib/parallel-api.js
test.js

Babel allows specifying plugins like so:
```javascript
["es2015", { "loose": true, "modules": false }]
```
Plugins setup like this are currently classified as not parallelizable, when they are in fact able to be serialized and passed to the worker processes just fine.
This change recognizes this plugin format and allows these to be parallelized.

Plugins specified as an array of serializable things can be parallelized

---

README.md
lib/parallel-api.js
test.js

Someday, after a major version bump we can consider making this true. But to ensure compatibility we will start off as false, but have stuff like ember-cli-babel’s tests choose true. 
Apps may also opt into true

Add throwUnlessParallelizable (defaulting to false).

---

README.md

The README incorrectly states that setting `JOBS=0` will disable parallelization. The check in [parallel-api.js](https://github.com/babel/broccoli-babel-transpiler/blob/master/lib/parallel-api.js) for the `JOBS` environment variable is:
```
const JOBS = Number(process.env.JOBS) || require('os').cpus().length;
```
`Number(0)` is a falsey value, so setting `JOBS=0` is equivalent to not setting `JOBS` at all, and will default to the number of CPUs. Setting `JOBS=1`  _does_ correctly disable parallelization, so that should be the only suggested approach.

Remove 'JOBS=0' from disable parallelization section of README

---

README.md
index.js
lib/parallel-api.js
tests/test.js

Throw when the plugin is constructed:
* automatically gives a more actionable stack trace
* fails fast, and fails even if that plugins persistent-filter were to skip the build
* add environment variable

Enhance throwUnlessParallelizable

---

lib/parallel-api.js

@rwjblue Ran into this while fixing tests on the `babel-7` branch of ember-cli-babel, now that it raises an exception if anything isn't parallelizable. Without this change, callbacks passed as plugin options won't be deserialized correctly, since they wind up in a nested array like:
```js
plugins: [
['foo-bar', { callback }]
]
```
It looks like the tests on this branch aren't super happy, though...

Deserialize nested arrays in the parallel API correctly

---

index.js
lib/parallel-api.js
tests/test.js

The cachekey is passed to worker to avoid calculating the cachekey again in `ember-cli-htmlbars-inline-precompile`

Pass cachekey to worker

---

lib/parallel-api.js
tests/test.js

This should resolve #158 
I've targeted the `v6.x` branch, since this bug is not limited to the 7.x release series.
/cc @stefanpenner @rwjblue

parallel-api: Fix "Cannot read property '_parallelBabel' of null" error

---

README.md
index.js
package.json
yarn.lock

The Babel polyfill is no longer provided in the @babel/core package but was moved to @babel/polyfill. This updates the plugin to:
* add `@babel/polyfill` as a dependency,
* grab the browser polyfill script from the new package in a platform-agnostic fashion,
* allow the consumer to configure the filename of the polyfill script in the output tree.
Fixes #161

Fix browser polyfill for Babel 7

---

lib/parallel-api.js
tests/utils/terminate-workers.js

In cd3f22c the interaction between the worker and the parent process changed (moving from referring to just the babel options to a hash of `{ babel, cacheKey }`). In general, this worked well on its own but since we dispatch to a worker pool that may have been setup by a different version of broccoli-babel-transpiler it introduced a mismatch.
Failure scenario:
Run a broccoli pipeline that contains both broccoli-babel-transpiler@7.0.0 and broccoli-babel-transpiler@7.1.0.
1) If the v7.0.0 plugin runs first, the worker pool that is created will **not** be aware of the `.babel` property and therefore it will throw the following error:
```
Unknown option: .babel
```
2) If the v7.1.0 plugin runs first, the worker pool that is created will always attempt to peal off a `.babel` property, but when …

Prevent mismatch between worker and host process.

---

index.js
package.json

I am working on https://github.com/gabrielcsapo/broccoli-inspector and a feature it has is to surface monitor related information to the user to provide information helpful debugging.
This information will surface the following:

[feature] adds heimdall monitor for logging information helpful for debugging babel process

---

README.md
index.js
tests/test.js

This should land before #187 because then there is a change in `test.js` that needs to be made in that branch

Remove browserPolyfill option

---

.travis.yml
appveyor.yml
index.js
package.json
tests/test.js
yarn.lock

Other addons converted to work with b-p-f v3 don't contain [this bit](https://github.com/babel/broccoli-babel-transpiler/blob/master/index.js#L36), but want to make sure that is okay.
```js
if (!(this instanceof Babel)) {
return new Babel(inputTree, _options);
}
```

Drop Node < 10 support; Upgrade to `broccoli-persistent-filter@3`

---

README.md
index.js
lib/options-hash.js
lib/parallel-api.js
tests/test-slow.js
tests/test.js

Moves Babel-specific options into their own object.
Closes #189

Separate Broccoli and Babel options

---

package.json
yarn.lock

References:
* [blog post](https://babeljs.io/blog/2020/10/15/7.12.0.html)
* [changelog](https://github.com/babel/babel/releases/tag/v7.12.0)

Update to `@babel/core@7.12.0`.

---

package.json
yarn.lock

`@babel/polyfill` was removed in #191 so is not longer needed as a dep
`yarn run tests:all` passes locally

Remove @babel/polyfill dependency

---

lib/parallel-api.js
lib/worker.js

The original code **never** handled the cases where `@babel/core`'s `transform` method throws an error, it just _happened_ to be that we didn't hit this case (because babel tended not to `throw` during parsing).
This updates to ensure that our worker will always resolve, sometimes with `{ code, metadata }` and other times (when an error happens) `{ error, stack }`. When we resolve with `{ error, stack }` the parent process will throw an error with that information (so that `ember build` exits non-zero, or `ember serve` shows the build failure and then rebuilds succesfully once the syntax error is fixed).
(cherry picked from #209)

[BACKPORT v7.x] Ensure the worker processes do not crash when parsing invalid syntax

---

lib/parallel-api.js
lib/worker.js

The original code **never** handled the cases where `@babel/core`'s `transform` method throws an error, it just _happened_ to be that we didn't hit this case (because babel tended not to `throw` during parsing).
This updates to ensure that our worker will always resolve, sometimes with `{ code, metadata }` and other times (when an error happens) `{ error, stack }`. When we resolve with `{ error, stack }` the parent process will throw an error with that information (so that `ember build` exits non-zero, or `ember serve` shows the build failure and then rebuilds succesfully once the syntax error is fixed).

Ensure the worker processes do not crash when parsing invalid syntax

---

package-lock.json
package.json

Analogue to https://github.com/babel/ember-cli-babel/pull/452 and related to https://github.com/babel/ember-cli-babel/issues/453.

[BREAKING] Move `@babel/core` to `peerDependencies` to resolve peer dependency warnings and errors

---

lib/parallel-api.js
lib/worker.js
tests/test.js
tests/utils/parallel-plugin.js

This allows people to use async babel plugins and babel plugins authored as ES modules.
It's a relatively small change since this package was already async in the right areas, it was just calling the synchronous babel APIs when it could use the async equivalent.
If we release this as a patch, everybody on ember-cli-babel 8.x will get it.

Support async babel plugins
